title: 'Moja strona'
author:
  name: 'Marcel Czowalla'
  email: 'kocietexty@gmail.com'

# This menu is at the root level (zero indentation)
# menu:
#   # # This dash is indented with 2 spaces
#   - text: 'Opieka nad grobem'
#     # These properties are indented with 4 spaces
#     url: '/uslugi'
#     icon: 'paint-brush'