title: 'Grav Site'
author:
  name: 'John Doe'
  email: 'john@email.com'

# This menu is at the root level (zero indentation)
menu:
  # This dash is indented with 2 spaces
  - text: 'Style Guide'
    # These properties are indented with 4 spaces
    url: '/styleguide'
    icon: 'paint-brush'
