server {
    listen 80 default_server;
    server_name _;

    root /var/www/html;
    index index.php; # Dodajemy index.php jako domyślny plik

    # Główne reguły przepisywania dla Grav
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Przekazywanie żądań PHP do kontenera PHP-FPM
    location ~ \.php$ {
        try_files $uri =404; # Jeśli plik .php nie istnieje, zwróć 404
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000; # 'php' to nazwa serwisu PHP-FPM z docker-compose.yml
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        # fastcgi_param HTTP_PROXY ""; # Można na razie zostawić, albo usunąć do testów
        # fastcgi_read_timeout 300; # Można na razie zostawić
    }

    # Na razie wyłączamy wszystkie specyficzne bloki deny i location dla /system, /user itp.
    # oraz szczegółowe keszowanie zasobów statycznych, aby uprościć.
}